# Generated by Django 4.2.5 on 2023-09-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0002_addusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addusers',
            name='user',
        ),
        migrations.AddField(
            model_name='addusers',
            name='designation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='addusers',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='addusers',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='addusers',
            name='pimage',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='addusers',
            name='qualification',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
